import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarApp from "@/components/layouts/Sidebar/Sidebar";
import { outfit } from "@/lib/font.utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${outfit.className} antialiased`}>
        <SidebarProvider>
          <SidebarApp />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
