import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SidebarApp from "@/components/layouts/Sidebar/Sidebar";
import { outfit } from "@/lib/font.utils";
import HeaderApp from "@/components/layouts/Header/Header";
import TanstackProvider from "@/providers/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${outfit.className} antialiased`}>
        <TanstackProvider>
          <SidebarProvider>
            <SidebarApp />

            <main className="w-full">
              <HeaderApp
                text="Lihat Dashboard Anda"
                textColor="text-blue-500"
              ></HeaderApp>
              <SidebarTrigger className="block md:hidden" />
              {children}
            </main>
          </SidebarProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
